// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ay-YxEOka70n6Hw7Yj_K7mpv2EkbwPQ',
    appId: '1:262527614202:web:6ec3c1bb3c1e701fde9d43',
    messagingSenderId: '262527614202',
    projectId: 'ecommerce-e55c7',
    authDomain: 'ecommerce-e55c7.firebaseapp.com',
    storageBucket: 'ecommerce-e55c7.appspot.com',
    measurementId: 'G-28BTWQ640T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5vxfW1fWkQ8Y3OIWgpl7VWKXFIhpP0SA',
    appId: '1:262527614202:android:04a5d02741e9e201de9d43',
    messagingSenderId: '262527614202',
    projectId: 'ecommerce-e55c7',
    storageBucket: 'ecommerce-e55c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD5PN0pn9m3woEGYvNKA5kjCQ2BS-28JI',
    appId: '1:262527614202:ios:71e059d36415a413de9d43',
    messagingSenderId: '262527614202',
    projectId: 'ecommerce-e55c7',
    storageBucket: 'ecommerce-e55c7.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD5PN0pn9m3woEGYvNKA5kjCQ2BS-28JI',
    appId: '1:262527614202:ios:f0fc208bea658cbfde9d43',
    messagingSenderId: '262527614202',
    projectId: 'ecommerce-e55c7',
    storageBucket: 'ecommerce-e55c7.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
